apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kube-vip-cloud-provider
rules:
  - apiGroups: ['coordination.k8s.io']
    resources: ['leases']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch']
  - apiGroups: ['']
    resources: ['services', 'services/status']
    verbs: ['get', 'list', 'watch', 'update', 'patch']
  - apiGroups: ['']
    resources: ['nodes', 'configmaps']
    verbs: ['get', 'list', 'watch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-vip-cloud-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-cloud-provider
subjects:
  - kind: ServiceAccount
    name: kube-vip-cloud-provider
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-vip-cloud-provider
  namespace: kube-system
  annotations:
    ignore-check.kube-linter.io/no-liveness-probe:
      'kube-vip-cloud-provider does not expose standard HTTP probes'
    ignore-check.kube-linter.io/no-readiness-probe:
      'kube-vip-cloud-provider does not expose standard HTTP probes'
    ignore-check.kube-linter.io/no-read-only-root-fs: 'Vendor image default'
    ignore-check.kube-linter.io/run-as-non-root: 'Vendor image default'
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kube-vip-cloud-provider
  template:
    metadata:
      labels:
        app: kube-vip-cloud-provider
    spec:
      # the goal is to keep this service for now away from the
      # rpi 3b+ worker node, all the rpi 5 are masters due to ha
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      serviceAccountName: kube-vip-cloud-provider
      containers:
        - name: kube-vip-cloud-provider
          image: ghcr.io/kube-vip/kube-vip-cloud-provider:v0.0.12
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          command:
            - /kube-vip-cloud-provider
            - --leader-elect-resource-name=plndr-cp-lock
            - --configmap-name=kubevip-configmap
          env:
            - name: LB_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
